#
# -*- coding: utf-8 -*-
# Copyright 2023 Ciena
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the waveserver5_pm module
"""
from __future__ import absolute_import, division, print_function


__metaclass__ = type


class PmArgs(object):  # pylint: disable=R0903
    """The arg spec for the waveserver5_pm module"""

    def __init__(self, **kwargs):
        pass

    argument_spec = {
        "config": {
            "type": "dict",
            "options": {
                "encryption_gcm_performance_instances": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "instance_name": {"type": "str", "required": True},
                        "properties": {
                            "type": "dict",
                            "options": {
                                "tca_profile_15_min": {"type": "str", "required": True},
                                "tca_profile_24_hr": {"type": "str", "required": True},
                                "tca_profile_untimed": {"type": "str", "required": True},
                            },
                        },
                        "state": {
                            "type": "dict",
                            "options": {
                                "admin_state": {"type": "str", "choices": ["disabled", "enabled"], "required": True},
                                "tca_admin_state": {
                                    "type": "str",
                                    "choices": ["disabled", "enabled"],
                                    "required": True,
                                },
                            },
                        },
                    },
                },
                "ethernet_performance_instances": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "instance_name": {"type": "str", "required": True},
                        "properties": {
                            "type": "dict",
                            "options": {
                                "tca_profile_15_min": {"type": "str", "required": True},
                                "tca_profile_24_hr": {"type": "str", "required": True},
                                "tca_profile_untimed": {"type": "str", "required": True},
                            },
                        },
                        "state": {
                            "type": "dict",
                            "options": {
                                "admin_state": {"type": "str", "choices": ["disabled", "enabled"], "required": True},
                                "tca_admin_state": {
                                    "type": "str",
                                    "choices": ["disabled", "enabled"],
                                    "required": True,
                                },
                            },
                        },
                    },
                },
                "global_config": {
                    "type": "dict",
                    "options": {
                        "admin_state": {"type": "str", "choices": ["disabled", "enabled"], "required": True},
                        "tca_admin_state": {"type": "str", "choices": ["disabled", "enabled"], "required": True},
                        "tca_notification_type": {
                            "type": "str",
                            "choices": ["summary-event", "summary-alarm", "event", "alarm"],
                            "required": True,
                        },
                        "untimed_read_and_clear": {"type": "str", "choices": ["disabled", "enabled"], "required": True},
                    },
                },
                "modem_performance_instances": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "instance_name": {"type": "str", "required": True},
                        "properties": {
                            "type": "dict",
                            "options": {
                                "tca_profile_15_min": {"type": "str", "required": True},
                                "tca_profile_24_hr": {"type": "str", "required": True},
                                "tca_profile_untimed": {"type": "str", "required": True},
                            },
                        },
                        "state": {
                            "type": "dict",
                            "options": {
                                "admin_state": {"type": "str", "choices": ["disabled", "enabled"], "required": True},
                                "tca_admin_state": {
                                    "type": "str",
                                    "choices": ["disabled", "enabled"],
                                    "required": True,
                                },
                            },
                        },
                    },
                },
                "odu_performance_instances": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "instance_name": {"type": "str", "required": True},
                        "properties": {
                            "type": "dict",
                            "options": {
                                "tca_profile_15_min": {"type": "str", "required": True},
                                "tca_profile_24_hr": {"type": "str", "required": True},
                                "tca_profile_untimed": {"type": "str", "required": True},
                            },
                        },
                        "state": {
                            "type": "dict",
                            "options": {
                                "admin_state": {"type": "str", "choices": ["disabled", "enabled"], "required": True},
                                "tca_admin_state": {
                                    "type": "str",
                                    "choices": ["disabled", "enabled"],
                                    "required": True,
                                },
                            },
                        },
                    },
                },
                "optical_power_instances": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "instance_name": {"type": "str", "required": True},
                        "properties": {
                            "type": "dict",
                            "options": {
                                "tca_profile_15_min": {"type": "str", "required": True},
                                "tca_profile_24_hr": {"type": "str", "required": True},
                                "tca_profile_untimed": {"type": "str", "required": True},
                            },
                        },
                        "state": {
                            "type": "dict",
                            "options": {
                                "admin_state": {"type": "str", "choices": ["disabled", "enabled"], "required": True},
                                "tca_admin_state": {
                                    "type": "str",
                                    "choices": ["disabled", "enabled"],
                                    "required": True,
                                },
                            },
                        },
                    },
                },
                "otu_performance_instances": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "instance_name": {"type": "str", "required": True},
                        "properties": {
                            "type": "dict",
                            "options": {
                                "tca_profile_15_min": {"type": "str", "required": True},
                                "tca_profile_24_hr": {"type": "str", "required": True},
                                "tca_profile_untimed": {"type": "str", "required": True},
                            },
                        },
                        "state": {
                            "type": "dict",
                            "options": {
                                "admin_state": {"type": "str", "choices": ["disabled", "enabled"], "required": True},
                                "tca_admin_state": {
                                    "type": "str",
                                    "choices": ["disabled", "enabled"],
                                    "required": True,
                                },
                            },
                        },
                    },
                },
                "photonics_instances": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "instance_name": {"type": "str", "required": True},
                        "properties": {
                            "type": "dict",
                            "options": {
                                "tca_profile_15_min": {"type": "str", "required": True},
                                "tca_profile_24_hr": {"type": "str", "required": True},
                                "tca_profile_untimed": {"type": "str", "required": True},
                            },
                        },
                        "state": {
                            "type": "dict",
                            "options": {
                                "admin_state": {"type": "str", "choices": ["disabled", "enabled"], "required": True},
                                "tca_admin_state": {
                                    "type": "str",
                                    "choices": ["disabled", "enabled"],
                                    "required": True,
                                },
                            },
                        },
                    },
                },
            },
        },
        "state": {"type": "str", "default": "merged", "choices": ["merged", "overridden", "gathered"]},
    }  # pylint: disable=C0301
