#
# -*- coding: utf-8 -*-
# Copyright 2023 Ciena
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the waveserver5_pm module
"""
from __future__ import absolute_import, division, print_function


__metaclass__ = type


class PmArgs(object):  # pylint: disable=R0903
    """The arg spec for the waveserver5_pm module"""

    def __init__(self, **kwargs):
        pass

    argument_spec = {
        "config": {
            "options": {
                "encryption_gcm_performance_instances": {
                    "options": {
                        "instance_name": {"required": True, "type": "str"},
                        "properties": {
                            "options": {
                                "tca_profile_15_min": {"required": True, "type": "str"},
                                "tca_profile_24_hr": {"required": True, "type": "str"},
                                "tca_profile_untimed": {"required": True, "type": "str"},
                            },
                            "type": "dict",
                        },
                        "state": {
                            "options": {
                                "admin_state": {"choices": ["disabled", "enabled"], "required": True, "type": "str"},
                                "tca_admin_state": {
                                    "choices": ["disabled", "enabled"],
                                    "required": True,
                                    "type": "str",
                                },
                            },
                            "type": "dict",
                        },
                    },
                    "type": "list",
                },
                "ethernet_performance_instances": {
                    "options": {
                        "instance_name": {"required": True, "type": "str"},
                        "properties": {
                            "options": {
                                "tca_profile_15_min": {"required": True, "type": "str"},
                                "tca_profile_24_hr": {"required": True, "type": "str"},
                                "tca_profile_untimed": {"required": True, "type": "str"},
                            },
                            "type": "dict",
                        },
                        "state": {
                            "options": {
                                "admin_state": {"choices": ["disabled", "enabled"], "required": True, "type": "str"},
                                "tca_admin_state": {
                                    "choices": ["disabled", "enabled"],
                                    "required": True,
                                    "type": "str",
                                },
                            },
                            "type": "dict",
                        },
                    },
                    "type": "list",
                },
                "global_config": {
                    "options": {
                        "admin_state": {"choices": ["disabled", "enabled"], "required": True, "type": "str"},
                        "tca_admin_state": {"choices": ["disabled", "enabled"], "required": True, "type": "str"},
                        "tca_notification_type": {
                            "choices": ["summary-event", "summary-alarm", "event", "alarm"],
                            "required": True,
                            "type": "str",
                        },
                        "untimed_read_and_clear": {"choices": ["disabled", "enabled"], "required": True, "type": "str"},
                    },
                    "type": "dict",
                },
                "modem_performance_instances": {
                    "options": {
                        "instance_name": {"required": True, "type": "str"},
                        "properties": {
                            "options": {
                                "tca_profile_15_min": {"required": True, "type": "str"},
                                "tca_profile_24_hr": {"required": True, "type": "str"},
                                "tca_profile_untimed": {"required": True, "type": "str"},
                            },
                            "type": "dict",
                        },
                        "state": {
                            "options": {
                                "admin_state": {"choices": ["disabled", "enabled"], "required": True, "type": "str"},
                                "tca_admin_state": {
                                    "choices": ["disabled", "enabled"],
                                    "required": True,
                                    "type": "str",
                                },
                            },
                            "type": "dict",
                        },
                    },
                    "type": "list",
                },
                "odu_performance_instances": {
                    "options": {
                        "instance_name": {"required": True, "type": "str"},
                        "properties": {
                            "options": {
                                "tca_profile_15_min": {"required": True, "type": "str"},
                                "tca_profile_24_hr": {"required": True, "type": "str"},
                                "tca_profile_untimed": {"required": True, "type": "str"},
                            },
                            "type": "dict",
                        },
                        "state": {
                            "options": {
                                "admin_state": {"choices": ["disabled", "enabled"], "required": True, "type": "str"},
                                "tca_admin_state": {
                                    "choices": ["disabled", "enabled"],
                                    "required": True,
                                    "type": "str",
                                },
                            },
                            "type": "dict",
                        },
                    },
                    "type": "list",
                },
                "optical_power_instances": {
                    "options": {
                        "instance_name": {"required": True, "type": "str"},
                        "properties": {
                            "options": {
                                "tca_profile_15_min": {"required": True, "type": "str"},
                                "tca_profile_24_hr": {"required": True, "type": "str"},
                                "tca_profile_untimed": {"required": True, "type": "str"},
                            },
                            "type": "dict",
                        },
                        "state": {
                            "options": {
                                "admin_state": {"choices": ["disabled", "enabled"], "required": True, "type": "str"},
                                "tca_admin_state": {
                                    "choices": ["disabled", "enabled"],
                                    "required": True,
                                    "type": "str",
                                },
                            },
                            "type": "dict",
                        },
                    },
                    "type": "list",
                },
                "otu_performance_instances": {
                    "options": {
                        "instance_name": {"required": True, "type": "str"},
                        "properties": {
                            "options": {
                                "tca_profile_15_min": {"required": True, "type": "str"},
                                "tca_profile_24_hr": {"required": True, "type": "str"},
                                "tca_profile_untimed": {"required": True, "type": "str"},
                            },
                            "type": "dict",
                        },
                        "state": {
                            "options": {
                                "admin_state": {"choices": ["disabled", "enabled"], "required": True, "type": "str"},
                                "tca_admin_state": {
                                    "choices": ["disabled", "enabled"],
                                    "required": True,
                                    "type": "str",
                                },
                            },
                            "type": "dict",
                        },
                    },
                    "type": "list",
                },
                "photonics_instances": {
                    "options": {
                        "instance_name": {"required": True, "type": "str"},
                        "properties": {
                            "options": {
                                "tca_profile_15_min": {"required": True, "type": "str"},
                                "tca_profile_24_hr": {"required": True, "type": "str"},
                                "tca_profile_untimed": {"required": True, "type": "str"},
                            },
                            "type": "dict",
                        },
                        "state": {
                            "options": {
                                "admin_state": {"choices": ["disabled", "enabled"], "required": True, "type": "str"},
                                "tca_admin_state": {
                                    "choices": ["disabled", "enabled"],
                                    "required": True,
                                    "type": "str",
                                },
                            },
                            "type": "dict",
                        },
                    },
                    "type": "list",
                },
            },
            "type": "dict",
        },
        "state": {"choices": ["merged", "overridden", "gathered"], "default": "merged", "type": "str"},
    }  # pylint: disable=C0301
