---
namespace: ciena
name: waveserver5
version: 0.0.2
readme: README.md
dependencies:
  ansible.netcommon: ">=2.5.1"
authors:
  - Jeff Groom (github.com/jgroom33)
  - Galo Ertola (github.com/perrary)
# description: null
license_file: LICENSE
tags: [ciena, waveserver, networking, ethernet, netconf, optical, dwdm]
repository: https://github.com/ciena/ciena.waveserver5
homepage: https://github.com/ciena/ciena.waveserver5
issues: https://github.com/ciena/ciena.waveserver5/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
  - .vscode
  - .github
