# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: ciena
name: waveserver5
version: 0.0.1
readme: README.md
dependencies:
  ansible.netcommon: ">=2.5.1"
authors:
  - Jeff Groom (github.com/jgroom33)
  - Galo Ertola (github.com/perrary)
description: null
license_file: LICENSE
tags: [ciena, waveserver, networking, ethernet, netconf, optical, dwdm]
repository: https://github.com/ciena/ciena.waveserver5
# documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/ciena/ciena.waveserver5
issues: https://github.com/ciena/ciena.waveserver5/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
  - .vscode
  - .github
