#
# -*- coding: utf-8 -*-
# Copyright 2023 Ciena
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the waveserver5_ptps module
"""
from __future__ import absolute_import, division, print_function


__metaclass__ = type


class PtpsArgs(object):  # pylint: disable=R0903
    """The arg spec for the waveserver5_ptps module"""

    def __init__(self, **kwargs):
        pass

    argument_spec = {
        "config": {
            "elements": "dict",
            "options": {
                "properties": {
                    "options": {
                        "forward_error_correction": {
                            "choices": ["disabled", "enabled"],
                            "required": True,
                            "type": "str",
                        },
                        "is_coherent": {"required": True, "type": "bool"},
                        "thresholds": {
                            "options": {
                                "hccs_db": {"required": True, "type": "float"},
                                "pre_fec_sd_db": {"required": True, "type": "float"},
                                "pre_fec_sf_db": {"required": True, "type": "float"},
                            },
                            "type": "dict",
                        },
                        "transmitter": {
                            "options": {
                                "state": {
                                    "choices": ["disabled", "enabled", "not-applicable"],
                                    "required": True,
                                    "type": "str",
                                }
                            },
                            "type": "dict",
                        },
                        "type": {
                            "choices": [
                                "unknown",
                                "WLAi",
                                "WLAi-iOPS",
                                "4x25G",
                                "10G",
                                "OCH",
                                "OSC",
                                "OSC-Add-Drop",
                                "OTM",
                                "WL5e",
                                "WL5n",
                                "100G",
                                "4x100G",
                                "8x50G",
                                "2x50G",
                                "400ZR",
                            ],
                            "required": True,
                            "type": "str",
                        },
                        "xcvr_type": {
                            "choices": [
                                "not-available",
                                "unsupported",
                                "QSFPplus",
                                "QSFP28",
                                "WaveLogic " "3 " "Extreme",
                                "WaveLogic " "Ai",
                                "SFP",
                                "none",
                                "QSFP-DD",
                                "WaveLogic " "5e",
                            ],
                            "required": True,
                            "type": "str",
                        },
                    },
                    "type": "dict",
                },
                "ptp_id": {"required": True, "type": "str"},
                "state": {
                    "options": {
                        "admin_state": {"choices": ["disabled", "enabled"], "required": True, "type": "str"},
                        "spli_management": {"choices": ["disabled", "enabled"], "required": True, "type": "str"},
                    },
                    "type": "dict",
                },
            },
            "type": "list",
        },
        "state": {"choices": ["gathered", "merged", "overridden"], "default": "merged", "type": "str"},
    }  # pylint: disable=C0301
