#
# -*- coding: utf-8 -*-
# Copyright 2023 Ciena
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the waveserver5_aaa module
"""
from __future__ import absolute_import, division, print_function


__metaclass__ = type


class AaaArgs(object):  # pylint: disable=R0903
    """The arg spec for the waveserver5_aaa module"""

    def __init__(self, **kwargs):
        pass

    argument_spec = {
        "config": {
            "type": "dict",
            "options": {
                "authentication": {
                    "type": "dict",
                    "options": {
                        "authentication_method": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "type": {
                                    "type": "str",
                                    "choices": ["local", "radius", "tacacs", "radsec"],
                                    "required": True,
                                },
                                "priority": {"type": "int"},
                                "scope": {"type": "str", "choices": ["all", "serial", "remote"]},
                            },
                        }
                    },
                },
                "user_management": {
                    "type": "dict",
                    "options": {
                        "min_password_length": {"type": "int"},
                        "max_login_attempt": {"type": "int"},
                        "lockout_interval": {"type": "int"},
                    },
                },
                "user": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "user_name": {"type": "str"},
                        "password": {"type": "str", "no_log": True},
                        "secret": {"type": "str", "no_log": True},
                        "access_level": {
                            "type": "str",
                            "choices": ["limited", "admin", "super", "diag"],
                            "required": True,
                        },
                    },
                },
                "tacacs": {
                    "type": "dict",
                    "options": {
                        "global_config": {
                            "type": "dict",
                            "options": {
                                "admin_state": {"type": "str", "choices": ["disabled", "enabled"]},
                                "authentication_admin_state": {"type": "str", "choices": ["disabled", "enabled"]},
                                "authorization_admin_state": {"type": "str", "choices": ["disabled", "enabled"]},
                                "accounting_admin_state": {"type": "str", "choices": ["disabled", "enabled"]},
                                "accounting_command_enabled": {"type": "bool"},
                                "accounting_session_enabled": {"type": "bool"},
                                "syslog_admin_state": {"type": "str", "choices": ["disabled", "enabled"]},
                                "global_servers": {"type": "str", "choices": ["off", "on"]},
                                "search_method": {"type": "str", "choices": ["priority", "cached"]},
                                "privilege_level_admin": {"type": "int"},
                                "privilege_level_super": {"type": "int"},
                                "privilege_level_diag": {"type": "int"},
                                "timeout": {"type": "int"},
                                "key": {"type": "str"},
                                "key_min_length": {"type": "int"},
                                "secret": {"type": "str", "no_log": True},
                            },
                        },
                        "server": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "address": {"type": "str"},
                                "admin_state": {"type": "str", "choices": ["disabled", "enabled"]},
                                "priority": {"type": "int", "required": True},
                                "tcp_port": {"type": "int"},
                                "timeout": {"type": "int"},
                                "key": {"type": "str"},
                                "secret": {"type": "str", "no_log": True},
                            },
                        },
                        "authentication_server": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "address": {"type": "str"},
                                "admin_state": {"type": "str", "choices": ["disabled", "enabled"]},
                                "priority": {"type": "int", "required": True},
                                "tcp_port": {"type": "int"},
                                "timeout": {"type": "int"},
                                "key": {"type": "str"},
                                "secret": {"type": "str", "no_log": True},
                            },
                        },
                        "authorization_server": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "address": {"type": "str"},
                                "admin_state": {"type": "str", "choices": ["disabled", "enabled"]},
                                "priority": {"type": "int", "required": True},
                                "tcp_port": {"type": "int"},
                                "timeout": {"type": "int"},
                                "key": {"type": "str"},
                                "secret": {"type": "str", "no_log": True},
                            },
                        },
                        "accounting_server": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "address": {"type": "str"},
                                "admin_state": {"type": "str", "choices": ["disabled", "enabled"]},
                                "priority": {"type": "int", "required": True},
                                "tcp_port": {"type": "int"},
                                "timeout": {"type": "int"},
                                "key": {"type": "str"},
                                "secret": {"type": "str", "no_log": True},
                            },
                        },
                    },
                },
                "radius": {
                    "type": "dict",
                    "options": {
                        "global_config": {
                            "type": "dict",
                            "options": {
                                "admin_state": {"type": "str", "choices": ["disabled", "enabled"]},
                                "timeout": {"type": "int"},
                                "search_method": {"type": "str", "choices": ["priority", "cached"]},
                                "key": {"type": "str"},
                                "secret": {"type": "str", "no_log": True},
                                "retries": {"type": "int"},
                            },
                        },
                        "server": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "address": {"type": "str"},
                                "admin_state": {"type": "str", "choices": ["disabled", "enabled"]},
                                "priority": {"type": "int", "required": True},
                                "udp_port": {"type": "int"},
                            },
                        },
                    },
                },
                "radsec": {
                    "type": "dict",
                    "options": {
                        "global_config": {
                            "type": "dict",
                            "options": {
                                "admin_state": {"type": "str", "choices": ["disabled", "enabled"]},
                                "timeout": {"type": "int"},
                                "search_method": {"type": "str", "choices": ["priority", "cached"]},
                                "certificate_name": {"type": "str"},
                                "check_ip_host": {"type": "str", "choices": ["disabled", "enabled"]},
                                "check_fingerprint": {"type": "str", "choices": ["disabled", "enabled"]},
                            },
                        },
                        "ocsp_config": {
                            "type": "dict",
                            "options": {
                                "admin_state": {"type": "str", "choices": ["disabled", "enabled"]},
                                "responder_preference": {"type": "str", "choices": ["aia", "default-responder"]},
                                "default_responder": {"type": "str"},
                                "nonce": {"type": "str", "choices": ["off", "on"]},
                            },
                        },
                        "server": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "address": {"type": "str"},
                                "admin_state": {"type": "str", "choices": ["disabled", "enabled"]},
                                "priority": {"type": "int", "required": True},
                                "port": {"type": "int"},
                                "trusted_dns": {"type": "str"},
                                "trusted_fingerprint": {"type": "str"},
                            },
                        },
                    },
                },
            },
        },
        "state": {"type": "str", "default": "merged", "choices": ["merged", "overridden", "gathered"]},
    }  # pylint: disable=C0301
